// Generated by _generator/generate.py -- DO NOT EDIT DIRECTLY
function transform(input) {
  const channel = (input && input.rss && input.rss.channel) || (input && input.channel) || {};
  const rawItems = channel.item;
  const items = Array.isArray(rawItems) ? rawItems : (rawItems ? [rawItems] : []);
  const first = items[0] || {};

  const txt = (v) => {
    if (v == null) return '';
    if (typeof v === 'string') return v;
    if (typeof v === 'object') return v._text || v['#text'] || v.__cdata || v._cdata || '';
    return String(v);
  };

  const description = txt(first.description);
  const imgMatch = description.match(/<img[^>]+src=["']([^"']+)["']/i);
  const imageUrl = imgMatch ? imgMatch[1] : null;

  return {
    comic: {
      title: txt(first.title),
      link: txt(first.link),
      pub_date: txt(first.pubDate),
      image_url: imageUrl
    }
  };
}
