---
strategy: static
no_screen_padding: 'yes'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://www.comicsrss.com/rss/beware-of-toddler.rss
polling_headers: ''
polling_body: ''
id: 131760
custom_fields:
- keyname: doesnt_matter
  name: Daily New Yorker Cartoon
  field_type: author_bio
  description: Displays the Daily New Yorker Cartoon
  github_url: https://github.com/lanrat/trmnl_plugins
  learn_more_url: https://github.com/lanrat/trmnl_plugins/tree/main/Daily%20New%20Yorker%20Cartoon
name: Daily New Yorker Cartoon
refresh_interval: 120
