---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: 2.3.7
serverless_language: node
polling_url: https://makerworld.com/api/v1/search-service/select/design/nav?navKey=Trending&offset=0&limit=20
polling_headers: ''
polling_body: ''
id: 272038
oauth_enabled: 'false'
oauth_pkce_enabled: 'no'
oauth_authorize_url: ''
oauth_token_url: ''
oauth_scopes: ''
oauth_scope_separator: ''
oauth_refresh_url: ''
oauth_auth_params: ''
oauth_token_headers: ''
oauth_token_site: ''
oauth_token_params: ''
oauth_token_request_auth_method: ''
oauth_body_format: ''
oauth_token_response_metadata: ''
oauth_authorization_method: ''
oauth_refresh_params: ''
oauth_token_field_name: ''
oauth_expiry_field_name: ''
oauth_expiry_strategy: ''
oauth_fixed_expiry_ms: ''
custom_fields:
- keyname: doesnt_matter
  name: MakerWorld Trending Models
  category: discovery
  field_type: author_bio
  description: Show Trending projects from MakerWorld
  github_url: https://github.com/lanrat/trmnl_plugins
name: MakerWorld Trending Models
description:
refresh_interval: 360
